Load the GlobalLandTemperatures.csv file into a DataFrame in your notebook. How many observations are included in the file?

In [1]:
import pandas as pd
df = pd.read_csv('GlobalTempData.csv')
df

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1819-01-01,7.962,2.870,Baghdad,Iraq,32.95N,45.00E
1,1819-02-01,10.974,2.966,Baghdad,Iraq,32.95N,45.00E
2,1819-03-01,14.239,4.436,Baghdad,Iraq,32.95N,45.00E
3,1819-04-01,20.633,1.936,Baghdad,Iraq,32.95N,45.00E
4,1819-05-01,NaN,NaN,Baghdad,Iraq,32.95N,45.00E
...,...,...,...,...,...,...,...
95662,5/1/13,18.979,0.807,Xian,China,34.56N,108.97E
95663,6/1/13,23.522,0.647,Xian,China,34.56N,108.97E
95664,7/1/13,25.251,1.042,Xian,China,34.56N,108.97E
95665,8/1/13,24.528,0.840,Xian,China,34.56N,108.97E
95666,9/1/13,NaN,NaN,Xian,China,34.56N,108.97E

How many missing values (NaN) occur in the dataset?

In [4]:
Nan_count = df.isnull().sum()
print(Nan_count)
print(Nan_count.sum())

dt                                  0
AverageTemperature               3892
AverageTemperatureUncertainty    3892
City                                0
Country                             0
Latitude                            0
Longitude                           0
dtype: int64
7784

Filter the data by the city specified. How many observations are left for that city once the NaNs are removed?

In [5]:
df = df.dropna()
df

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1819-01-01,7.962,2.870,Baghdad,Iraq,32.95N,45.00E
1,1819-02-01,10.974,2.966,Baghdad,Iraq,32.95N,45.00E
2,1819-03-01,14.239,4.436,Baghdad,Iraq,32.95N,45.00E
3,1819-04-01,20.633,1.936,Baghdad,Iraq,32.95N,45.00E
5,1819-06-01,30.674,2.876,Baghdad,Iraq,32.95N,45.00E
...,...,...,...,...,...,...,...
95661,4/1/13,12.563,1.823,Xian,China,34.56N,108.97E
95662,5/1/13,18.979,0.807,Xian,China,34.56N,108.97E
95663,6/1/13,23.522,0.647,Xian,China,34.56N,108.97E
95664,7/1/13,25.251,1.042,Xian,China,34.56N,108.97E
95665,8/1/13,24.528,0.840,Xian,China,34.56N,108.97E

Compute the average temperature, in degrees Celsius, for the city chosen in class. Include 1 decimal value in your answer.

In [8]:
avg_temp = df['AverageTemperature'].mean()
print(f"The average temperature is: {avg_temp:.1f} °C")

The average temperature is: 18.3 °C

In [10]:
jakarta_rows = df[df['City'] == 'Jakarta']
jakarta_rows

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
40304,1825-01-01,26.322,2.283,Jakarta,Indonesia,5.63S,106.55E
40305,1825-02-01,26.070,1.321,Jakarta,Indonesia,5.63S,106.55E
40306,1825-03-01,26.670,1.916,Jakarta,Indonesia,5.63S,106.55E
40307,1825-04-01,27.408,2.133,Jakarta,Indonesia,5.63S,106.55E
40308,1825-05-01,26.975,1.153,Jakarta,Indonesia,5.63S,106.55E
...,...,...,...,...,...,...,...
42563,4/1/13,27.642,0.766,Jakarta,Indonesia,5.63S,106.55E
42564,5/1/13,27.936,0.230,Jakarta,Indonesia,5.63S,106.55E
42565,6/1/13,27.879,0.553,Jakarta,Indonesia,5.63S,106.55E
42566,7/1/13,26.858,0.790,Jakarta,Indonesia,5.63S,106.55E
42567,8/1/13,26.869,0.418,Jakarta,Indonesia,5.63S,106.55E

In [12]:
jakarta_avg_temp = jakarta_rows['AverageTemperature'].mean()
print(f"The average temperature in Jakarta is: {jakarta_avg_temp:.1f} °C")

The average temperature in Jakarta is: 26.5 °C

Do you think this average temperature is accurate? Name one factor that could lead to inaccuracy in the calculation.