## Lecture 15 Notebook - Combining Datasets

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('df1.csv')
df2 = pd.read_csv('df2.csv')
df1

    A   B   C
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [3]:
df2

    A   B   C
0  a4  b4  c4
1  a5  b5  c5
2  a6  b6  c6
3  a7  b7  c7

In [4]:
row_concat = pd.concat([df1, df2])
row_concat

    A   B   C
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
0  a4  b4  c4
1  a5  b5  c5
2  a6  b6  c6
3  a7  b7  c7

In [5]:
row_concat = pd.concat([df1, df2], ignore_index=True)
row_concat

    A   B   C
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
4  a4  b4  c4
5  a5  b5  c5
6  a6  b6  c6
7  a7  b7  c7

In [6]:
col_concat = pd.concat([df1, df2], axis=1)
col_concat

    A   B   C   A   B   C
0  a0  b0  c0  a4  b4  c4
1  a1  b1  c1  a5  b5  c5
2  a2  b2  c2  a6  b6  c6
3  a3  b3  c3  a7  b7  c7

In [7]:
col_concat['newcol'] = ['a', 'b', 'c', 'd']
col_concat

    A   B   C   A   B   C newcol
0  a0  b0  c0  a4  b4  c4      a
1  a1  b1  c1  a5  b5  c5      b
2  a2  b2  c2  a6  b6  c6      c
3  a3  b3  c3  a7  b7  c7      d

In [8]:
col_concat = pd.concat([df1, df2], axis=1, ignore_index=True)
col_concat

    0   1   2   3   4   5
0  a0  b0  c0  a4  b4  c4
1  a1  b1  c1  a5  b5  c5
2  a2  b2  c2  a6  b6  c6
3  a3  b3  c3  a7  b7  c7

In [9]:
df_merge = df1.merge(df2)
df_merge

Empty DataFrame
Columns: [A, B, C]
Index: []

In [10]:
df = pd.read_csv('petdata.csv')
df

    Unnamed: 0 petname  months  weight
0            0    Spot       4     2.1
1            1    Spot       8     5.8
2            2    Spot      10     7.5
3            3    Spot      14     8.9
4            4    Spot      18     9.2
5            5  Lassie       4     6.0
6            6  Lassie       8    15.1
7            7  Lassie      12    21.9
8            8  Lassie      14    23.0
9            9  Lassie      16    24.1
10          10    Fido       3    10.2
11          11    Fido       8    64.1
12          12    Fido      10    89.3
13          13    Fido      14    99.3
14          14    Fido      18   102.1

In [11]:
df = df.drop(columns=['Unnamed: 0'], axis=1)
df

   petname  months  weight
0     Spot       4     2.1
1     Spot       8     5.8
2     Spot      10     7.5
3     Spot      14     8.9
4     Spot      18     9.2
5   Lassie       4     6.0
6   Lassie       8    15.1
7   Lassie      12    21.9
8   Lassie      14    23.0
9   Lassie      16    24.1
10    Fido       3    10.2
11    Fido       8    64.1
12    Fido      10    89.3
13    Fido      14    99.3
14    Fido      18   102.1

In [12]:
breeders = pd.read_csv('pet_breeder.csv')
breeders

    petname          breeder
0      Spot       JK Kennels
1  Clifford  Public Breeders
2    Lassie      CBS Studios
3    Monica        Home Free

In [13]:
petbreeder_merge = df.merge(breeders)
petbreeder_merge

  petname  months  weight      breeder
0    Spot       4     2.1   JK Kennels
1    Spot       8     5.8   JK Kennels
2    Spot      10     7.5   JK Kennels
3    Spot      14     8.9   JK Kennels
4    Spot      18     9.2   JK Kennels
5  Lassie       4     6.0  CBS Studios
6  Lassie       8    15.1  CBS Studios
7  Lassie      12    21.9  CBS Studios
8  Lassie      14    23.0  CBS Studios
9  Lassie      16    24.1  CBS Studios

In [14]:
owners = pd.read_csv('pet_owner.csv')
owners

    Dogname         ownername
0      Spot        Jenn Smith
1  Clifford           Red Big
2    Lassie   Rudd Weatherwax
3    Monica     FreeMom Sally

In [15]:
badmerge = df.merge(owners, how='outer')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [ ]:
pet_merge = df.merge(owners, left_on='petname', right_on = 'Dogname')
pet_merge

In [ ]:
pet_merge_left = df.merge(owners, left_on='petname', right_on = 'Dogname', how = 'left')
pet_merge_left

In [ ]:
pet_merge_left2 = df.merge(breeders, how = 'left')
pet_merge_left2

In [ ]:
pet_merge_right = df.merge(owners, left_on='petname', right_on = 'Dogname', how = 'outer')
pet_merge_right

In [ ]:
pet_merge_right2 = df.merge(breeders, how = 'outer')
pet_merge_right2