In [1]:
import pandas as pd
import plotly.express as px 
tips = pd.read_csv('tips.csv')
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [2]:
tdf = tips.groupby('size')['tip'].mean
tdf

In [3]:
fig = px.bar(tips, x="size", y="tip") 
fig.show()

In [4]:
tips["percent"] = tips["tip"]/tips["total_bill"]*100
tips

     total_bill   tip smoker   day    time  size    percent
0         16.99  1.01     No   Sun  Dinner     2   5.944673
1         10.34  1.66     No   Sun  Dinner     3  16.054159
2         21.01  3.50     No   Sun  Dinner     3  16.658734
3         23.68  3.31     No   Sun  Dinner     2  13.978041
4         24.59  3.61     No   Sun  Dinner     4  14.680765
..          ...   ...    ...   ...     ...   ...        ...
239       29.03  5.92     No   Sat  Dinner     3  20.392697
240       27.18  2.00    Yes   Sat  Dinner     2   7.358352
241       22.67  2.00    Yes   Sat  Dinner     2   8.822232
242       17.82  1.75     No   Sat  Dinner     2   9.820426
243       18.78  3.00     No  Thur  Dinner     2  15.974441

[244 rows x 7 columns]

In [ ]:
newtip = tips[["size", "percent"]]
newtip

     size    percent
0       2   5.944673
1       3  16.054159
2       3  16.658734
3       2  13.978041
4       4  14.680765
..    ...        ...
239     3  20.392697
240     2   7.358352
241     2   8.822232
242     2   9.820426
243     2  15.974441

[244 rows x 2 columns]

In [6]:
# Creating the Figure instance
fig = px.scatter(newtip, x="size", y="percent") 
 
# showing the plot
fig.show()

In [11]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
# Create the figure:
# x-axis: 'sex', y-axis: 'total_bill'
# color the bars by 'smoker' status, group them by 'day'
fig = px.bar(df, x="sex", y="total_bill", color="smoker", barmode="group", facet_col="day")

# Display the interactive figure
fig.show()